# Generated by Django 2.0.3 on 2018-04-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180411_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='basemaps',
            field=models.ManyToManyField(blank=True, to='profiles.Basemap'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otherfiles',
            field=models.ManyToManyField(blank=True, to='profiles.Otherfiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spatialdbs',
            field=models.ManyToManyField(blank=True, to='profiles.Spatialdbs'),
        ),
    ]
