# Generated by Django 2.0.3 on 2018-04-12 00:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180411_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='size',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='spatialdbs',
            name='size',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='spatialdbs',
            name='visible',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None),
        ),
    ]
