# Generated by Django 2.0.3 on 2018-04-12 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_auto_20180412_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatVersion', models.FloatField(default=1.1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
                ('profiles', models.ManyToManyField(blank=True, to='profiles.Profile')),
            ],
        ),
    ]
