# Generated by Django 2.0.3 on 2018-04-12 01:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_profilelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileList',
            new_name='ProfileSet',
        ),
    ]
