# Generated by Django 2.0.3 on 2018-04-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180412_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spatialdbs',
            new_name='Spatialitedbs',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='spatialdbs',
            new_name='spatialitedbs',
        ),
    ]
