# Generated by Django 2.0.3 on 2018-04-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20180414_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='projects',
            new_name='project',
        ),
    ]
